name: DeathBans
main: com.alexneises.deathbans
version: 3.3
description: Provides deathbans.
author: walterrocks91
commands:
  deathbans:
    description: Base deathbans command.
    usage: /<command>
  db:
    description: Base deathbans command.
    usage: /<command>